apiVersion: v1
kind: Service
metadata:
  name: enterprise-eks-service
  namespace: enterprise-app
spec:
  selector:
    app: enterprise-eks-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP